# Docker Compose

version: "3.8"

services:
  immich-swipe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: immich-swipe
    restart: unless-stopped
    ports:
      - "2293:80"

